In [ ]:
import pandas as pd
from collections import Counter
from tqdm import tqdm
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import adjusted_mutual_info_score

In [ ]:
df = pd.read_excel('/content/final_df.xlsx')

In [ ]:
df = pd.read_csv('/content/SUHI_MATRIX_WITH_CHW_Notes_10_29_2024_with_combined_notes.csv')

In [ ]:
raw_df = pd.read_csv('/content/CAP_Postdischarge_data_16FEB24.xlsx - coded.csv')

<ipython-input-2-0519b1432828>:1: DtypeWarning: Columns (100,110,130,147,161,168,173,178,194,198,214,226,254,259,274,276,283,293,297,303,310,366,379,381,384,386,390,392,401,403,406,411,414,417,419,422,424,427,430,433,435,438,444,446,449,451,454,456,459,461,468,472,474,476,480,484,486,489) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_df = pd.read_csv('/content/CAP_Postdischarge_data_16FEB24.xlsx - coded.csv')

In [ ]:
df

,record_id,new_patient,visit_number,referral_date,day_readmit,age,sex_Male,Hispanic,AfricanAmerican,White,...,notes_contact3,notes_contact4,notes_contact5,notes_contact6,notes_contact7,notes_contact8,notes_contact9,notes_contact10,additional_contact_notes,anything_else
0,2,0.0,1,2021-04-12,0.0,66.0,0.0,0.0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,0.0,2,2021-05-26,NaN,NaN,0.0,0.0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,1.0,1,2021-04-12,1.0,50.0,0.0,0.0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patient not available
3,5,1.0,1,2021-04-12,0.0,61.0,1.0,0.0,1,0,...,EMOTIONAL SUPPORT,CLOSED CASE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,0.0,2,2021-09-23,0.0,59.0,1.0,0.0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2615,2311,1.0,1,2024-02-12,NaN,60.0,1.0,0.0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2616,2312,1.0,1,2024-02-12,NaN,35.0,0.0,1.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2617,2313,1.0,1,2024-02-13,NaN,49.0,1.0,1.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2618,2314,1.0,1,2024-02-13,NaN,62.0,1.0,1.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2619,2315,1.0,1,2024-02-12,NaN,29.0,1.0,1.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
raw_df

,7,redcap_event_name,new_patient,type_id,chw_name,inperson_connection,sw_date,referral_date,referral_month,referral_source,...,no_resources_healthed_expl,sdoh_other,sdoh_other_notes,resources_other,resources_other_notes,no_resources_other,no_resources_other_other,sdoh_notes,nowpow,old_sdoh_questionnaire_complete
0,2,round_1_arm_1,0.0,1.0,3.0,NaN,4/12/2021,4/12/2021,2104.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
1,2,round_2_arm_1,0.0,1.0,3.0,NaN,5/24/2021,5/26/2021,2105.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,4,round_1_arm_1,1.0,1.0,2.0,NaN,4/12/2021,4/12/2021,2104.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,5,round_1_arm_1,1.0,1.0,2.0,NaN,4/12/2021,4/12/2021,2104.0,1.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2
4,5,round_2_arm_1,0.0,1.0,2.0,NaN,9/21/2021,9/23/2021,2109.0,1.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2615,2311,round_1_arm_1,1.0,1.0,2.0,0.0,2/9/2024,2/12/2024,2402.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2616,2312,round_1_arm_1,1.0,1.0,10.0,0.0,2/9/2024,2/12/2024,2402.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2617,2313,round_1_arm_1,1.0,1.0,5.0,0.0,2/9/2024,2/13/2024,2402.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2618,2314,round_1_arm_1,1.0,1.0,5.0,0.0,2/9/2024,2/13/2024,2402.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2619,2315,round_1_arm_1,1.0,1.0,9.0,0.0,2/9/2024,2/12/2024,2402.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [ ]:
# Group by ID and check for age trends
def check_trend(group):
    age_diff = group['age'].diff().dropna()
    if (age_diff < 0).any():
        return 'Decreasing'
    elif (age_diff > 0).any():
        return 'Increasing'
    else:
        return 'Constant'

age_trend_lst = df.groupby('record_id').apply(check_trend).reset_index(name='Trend')

print(Counter(age_trend_lst['Trend']))

Counter({'Constant': 2070, 'Increasing': 104, 'Decreasing': 3})

<ipython-input-5-f405c79cdb49>:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  age_trend_lst = df.groupby('record_id').apply(check_trend).reset_index(name='Trend')

In [ ]:
inconsistent_vals_dict = {}
inconsistent_vals_report_dict = {}
for col in tqdm(df.groupby('record_id').nunique().reset_index().columns):
  inconsistent_vals_report_dict[col] = Counter(df.groupby('record_id').nunique().reset_index()[col])
  unique_records_count = Counter(df.groupby('record_id').nunique().reset_index()[col])[1] + Counter(df.groupby('record_id').nunique().reset_index()[col])[0]
  total_unique_record_ids = 2620 #2177
  inconsistent_vals_dict[col] = int((unique_records_count/total_unique_record_ids)*100)

100%|██████████| 116/116 [00:20<00:00,  5.70it/s]

In [ ]:
# Sort by keys before converting dict into a dataframe
inconsistent_vals_report_df = pd.DataFrame(inconsistent_vals_report_dict)

In [ ]:
inconsistent_vals_report_df

,record_id,new_patient,visit_number,referral_date,day_readmit,age,sex_Male,Hispanic,AfricanAmerican,White,...,notes_contact3,notes_contact4,notes_contact5,notes_contact6,notes_contact7,notes_contact8,notes_contact9,notes_contact10,additional_contact_notes,anything_else
2,1.0,219.0,224.0,219.0,135.0,103.0,NaN,NaN,NaN,NaN,...,38.0,13.0,8.0,5.0,1.0,1.0,1.0,NaN,1.0,29.0
4,1.0,NaN,21.0,18.0,NaN,2.0,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
5,1.0,NaN,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1.0,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2315,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1955.0,1874.0,1878.0,1984.0,1725.0,2136.0,2089.0,2177.0,2177.0,...,708.0,354.0,214.0,128.0,95.0,66.0,49.0,37.0,27.0,381.0
0,NaN,3.0,NaN,2.0,58.0,335.0,41.0,88.0,NaN,NaN,...,1424.0,1806.0,1954.0,2044.0,2081.0,2110.0,2127.0,2140.0,2149.0,1762.0
3,NaN,NaN,43.0,45.0,NaN,12.0,NaN,NaN,NaN,NaN,...,5.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0
7,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
inconsistent_vals_report_df.to_csv('inconsistent_vals_report_final_df.csv')

## Raw Data Analysis

In [ ]:
# Group by ID and check for age trends
def check_trend(group):
    age_diff = group['age'].diff().dropna()
    if (age_diff < 0).any():
        return 'Decreasing'
    elif (age_diff > 0).any():
        return 'Increasing'
    else:
        return 'Constant'

age_trend_lst = raw_df.groupby('7').apply(check_trend).reset_index(name='Trend')

print(Counter(age_trend_lst['Trend']))

Counter({'Constant': 2070, 'Increasing': 104, 'Decreasing': 3})

<ipython-input-4-bd6f93044c33>:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  age_trend_lst = raw_df.groupby('7').apply(check_trend).reset_index(name='Trend')

In [ ]:
inconsistent_vals_dict = {}
inconsistent_vals_report_dict = {}
for col in tqdm(raw_df.groupby('7').nunique().reset_index().columns):
  inconsistent_vals_report_dict[col] = Counter(raw_df.groupby('7').nunique().reset_index()[col])
  unique_records_count = Counter(raw_df.groupby('7').nunique().reset_index()[col])[1] + Counter(raw_df.groupby('7').nunique().reset_index()[col])[0]
  total_unique_record_ids = 2620 #2177
  inconsistent_vals_dict[col] = int((unique_records_count/total_unique_record_ids)*100)

100%|██████████| 492/492 [05:34<00:00,  1.47it/s]

In [ ]:
# Sort by keys before converting dict into a dataframe
inconsistent_vals_report_raw_df = pd.DataFrame(inconsistent_vals_report_dict)

In [ ]:
inconsistent_vals_report_raw_df.to_csv('inconsistent_vals_report_raw_data.csv')

## Filling missing values

In [ ]:
final_df = pd.read_excel('/content/final_df.xlsx')

In [ ]:
final_df_subset = final_df[['age', 'Hispanic', 'new_patient', 'visit_number', 'day_readmit', 'sex_Male', 'AfricanAmerican', 'White',
                  'Additional_race', 'language_English', 'language_Spanish', 'language_Other']]

In [ ]:
final_df_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2620 entries, 0 to 2619
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               2132 non-null   float64
 1   Hispanic          2506 non-null   float64
 2   new_patient       2612 non-null   float64
 3   visit_number      2620 non-null   int64
 4   day_readmit       2528 non-null   float64
 5   sex_Male          2577 non-null   float64
 6   AfricanAmerican   2620 non-null   int64
 7   White             2620 non-null   int64
 8   Additional_race   2620 non-null   int64
 9   language_English  2620 non-null   int64
 10  language_Spanish  2620 non-null   int64
 11  language_Other    2620 non-null   int64
dtypes: float64(5), int64(7)
memory usage: 245.8 KB

In [ ]:
final_df_subset.dropna(subset=['day_readmit'], inplace=True)

<ipython-input-43-2f02f7827ba8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df_subset.dropna(subset=['day_readmit'], inplace=True)

In [ ]:
final_df_subset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2528 entries, 0 to 2601
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               2047 non-null   float64
 1   Hispanic          2423 non-null   float64
 2   new_patient       2525 non-null   float64
 3   visit_number      2528 non-null   int64
 4   day_readmit       2528 non-null   float64
 5   sex_Male          2491 non-null   float64
 6   AfricanAmerican   2528 non-null   int64
 7   White             2528 non-null   int64
 8   Additional_race   2528 non-null   int64
 9   language_English  2528 non-null   int64
 10  language_Spanish  2528 non-null   int64
 11  language_Other    2528 non-null   int64
dtypes: float64(5), int64(7)
memory usage: 256.8 KB

In [ ]:
final_df_subset.isna().sum(axis=1).value_counts()

0    2017
1     422
2      63
3      26
Name: count, dtype: int64

In [ ]:
final_df_subset_with_na = final_df_subset[final_df_subset.isna().any(axis=1)]
final_df_subset_without_na = final_df_subset[~final_df_subset.isna().any(axis=1)]

In [ ]:
final_df_subset_with_na['day_readmit'].value_counts()

day_readmit
0.0    295
1.0    216
Name: count, dtype: int64

In [ ]:
final_df_subset_without_na['day_readmit'].value_counts()

day_readmit
0.0    1600
1.0     413
2.0       4
Name: count, dtype: int64

In [ ]:
final_df_subset_without_na

,age,Hispanic,new_patient,visit_number,day_readmit,sex_Male,AfricanAmerican,White,Additional_race,language_English,language_Spanish,language_Other
0,66.0,0.0,0.0,1,0.0,0.0,1,0,0,1,0,0
2,50.0,0.0,1.0,1,1.0,0.0,1,0,0,1,0,0
3,61.0,0.0,1.0,1,0.0,1.0,1,0,0,1,0,0
4,59.0,0.0,0.0,2,0.0,1.0,1,0,0,1,0,0
5,59.0,0.0,1.0,1,0.0,0.0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2574,29.0,0.0,1.0,1,1.0,1.0,1,0,0,1,0,0
2575,77.0,0.0,1.0,1,0.0,0.0,1,0,0,1,0,0
2577,24.0,0.0,1.0,1,0.0,1.0,1,0,0,1,0,0
2589,82.0,0.0,1.0,1,0.0,1.0,1,0,0,1,0,0
2601,39.0,0.0,0.0,2,2.0,0.0,1,0,0,1,0,0

In [ ]:
features_to_be_filled = ['Hispanic', 'new_patient', 'sex_Male']
for feature in features_to_be_filled:
  print(f"Filling missing values for {feature}")
  x_train, x_test, y_train, y_test = train_test_split(final_df_subset_without_na.drop(feature, axis=1), final_df_subset_without_na[feature], test_size=0.2, random_state=42)
  # Train a model to predict sex
  model = DecisionTreeClassifier()
  model.fit(x_train, y_train)
  y_pred = model.predict(x_test)
  accuracy = accuracy_score(y_test, y_pred)
  print(f"Accuracy: {accuracy}")
  print(f"Adjusted Mutual Info Score: {adjusted_mutual_info_score(y_test, y_pred)}")

Filling missing values for Hispanic
Accuracy: 0.9455445544554455
Adjusted Mutual Info Score: 0.583914130636178
Filling missing values for new_patient
Accuracy: 0.9529702970297029
Adjusted Mutual Info Score: 0.5651320761262121
Filling missing values for sex_Male
Accuracy: 0.5321782178217822
Adjusted Mutual Info Score: 0.0011399583957223838

In [ ]:
features_to_be_filled = ['age']
for feature in features_to_be_filled:
  print(f"Filling missing values for {feature}")
  x_train, x_test, y_train, y_test = train_test_split(final_df_subset_without_na.drop(feature, axis=1), final_df_subset_without_na[feature], test_size=0.2, random_state=42)
  # Train a model to predict sex
  model = DecisionTreeRegressor()
  model.fit(x_train, y_train)
  y_pred = model.predict(x_test)
  # Evaluate R-squared and Adjusted R-squared
  r2 = model.score(x_test, y_test)
  print(f"R-squared: {r2}")
  # Calculate Mean Squared Error
  mse = mean_squared_error(y_test, y_pred)
  print(f"Mean Squared Error: {mse}")
  print(f"Adjusted Mutual Info Score: {adjusted_mutual_info_score(y_test, y_pred)}")

Filling missing values for age
R-squared: -0.03918926221404684
Mean Squared Error: 297.80855851105775
Adjusted Mutual Info Score: 0.008136503284181296

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/cluster/_supervised.py:59: UserWarning: Clustering metrics expects discrete values but received multiclass values for label, and continuous values for target
  warnings.warn(msg, UserWarning)

# Min-Max Scaler on Age

In [ ]:

scaler = MinMaxScaler()
features_to_be_filled = ['Hispanic', 'new_patient', 'sex_Male']
for feature in features_to_be_filled:
  print(f"Filling missing values for {feature}")
  x_train, x_test, y_train, y_test = train_test_split(final_df_subset_without_na.drop(feature, axis=1), final_df_subset_without_na[feature], test_size=0.2, random_state=42)
  x_train['age'] = scaler.fit_transform(x_train[['age']])
  x_test['age'] = scaler.transform(x_test[['age']])
  # Train a model to predict sex
  model = KNeighborsClassifier()
  model.fit(x_train, y_train)
  y_pred = model.predict(x_test)
  accuracy = accuracy_score(y_test, y_pred)
  print(f"Accuracy: {accuracy}")
  print(f"Adjusted Mutual Info Score: {adjusted_mutual_info_score(y_test, y_pred)}")

Filling missing values for Hispanic
Accuracy: 0.9331683168316832
Adjusted Mutual Info Score: 0.5339167141296614
Filling missing values for new_patient
Accuracy: 0.9579207920792079
Adjusted Mutual Info Score: 0.6096019922267156
Filling missing values for sex_Male
Accuracy: 0.5470297029702971
Adjusted Mutual Info Score: 0.004554354464005826

In [ ]:
features_to_be_filled = ['age']
for feature in features_to_be_filled:
  print(f"Filling missing values for {feature}")
  x_train, x_test, y_train, y_test = train_test_split(final_df_subset_without_na.drop(feature, axis=1), final_df_subset_without_na[feature], test_size=0.2, random_state=42)
  # Train a model to predict sex
  model = KNeighborsRegressor()
  model.fit(x_train, y_train)
  y_pred = model.predict(x_test)
  # Evaluate R-squared and Adjusted R-squared
  r2 = model.score(x_test, y_test)
  print(f"R-squared: {r2}")
  # Calculate Mean Squared Error
  mse = mean_squared_error(y_test, y_pred)
  print(f"Mean Squared Error: {mse}")
  print(f"Adjusted Mutual Info Score: {adjusted_mutual_info_score(y_test, y_pred)}")

Filling missing values for age
R-squared: -0.26570166040678944
Mean Squared Error: 362.72198019801976
Adjusted Mutual Info Score: 0.008034132080215165

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/cluster/_supervised.py:59: UserWarning: Clustering metrics expects discrete values but received multiclass values for label, and continuous values for target
  warnings.warn(msg, UserWarning)